# Generated by Django 4.0 on 2021-12-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file_name', models.CharField(max_length=50)),
                ('csv_file', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='MuseumAPICSV',
            fields=[
                ('objectId', models.IntegerField(primary_key=True, serialize=False)),
                ('isHighlight', models.BooleanField()),
                ('accessionNumber', models.IntegerField()),
                ('accessionYear', models.IntegerField()),
                ('isPublicDomain', models.BooleanField()),
                ('primaryImage', models.ImageField(blank=True, null=True, upload_to='')),
                ('primaryImageSmall', models.ImageField(blank=True, null=True, upload_to='')),
                ('additionalImages', models.ImageField(blank=True, null=True, upload_to='')),
                ('department', models.CharField(max_length=50)),
                ('objectName', models.CharField(max_length=50)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('culture', models.CharField(blank=True, max_length=50, null=True)),
                ('period', models.CharField(blank=True, max_length=50, null=True)),
                ('dynasty', models.CharField(blank=True, max_length=50, null=True)),
                ('reign', models.CharField(blank=True, max_length=50, null=True)),
                ('portfolio', models.CharField(blank=True, max_length=50, null=True)),
                ('artistRole', models.CharField(blank=True, max_length=50, null=True)),
                ('artistPrefix', models.CharField(blank=True, max_length=50, null=True)),
                ('artistDisplayName', models.CharField(blank=True, max_length=50, null=True)),
                ('artistDisplayBio', models.CharField(blank=True, max_length=50, null=True)),
                ('artistSuffix', models.CharField(blank=True, max_length=50, null=True)),
                ('artistAlphaSort', models.CharField(blank=True, max_length=50, null=True)),
                ('artistNationality', models.CharField(blank=True, max_length=50, null=True)),
                ('artistBeginDate', models.DateField(blank=True, max_length=50, null=True)),
                ('artistEndDate', models.DateField(blank=True, max_length=50, null=True)),
                ('artistGender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=20)),
                ('artistWikidata_URL', models.CharField(blank=True, max_length=50, null=True)),
                ('artistULAN_URL', models.CharField(blank=True, max_length=50, null=True)),
                ('objectDate', models.DateField(blank=True, max_length=50, null=True)),
                ('objectBeginDate', models.DateField(blank=True, max_length=50, null=True)),
                ('objectEndDate', models.DateField(blank=True, max_length=50, null=True)),
                ('medium', models.CharField(blank=True, max_length=50, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=50, null=True)),
                ('measurements', models.CharField(blank=True, max_length=50, null=True)),
                ('creditLine', models.CharField(blank=True, max_length=50, null=True)),
                ('geographyType', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('county', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
                ('subregion', models.CharField(blank=True, max_length=50, null=True)),
                ('locale', models.CharField(blank=True, max_length=50, null=True)),
                ('locus', models.CharField(blank=True, max_length=50, null=True)),
                ('excavation', models.CharField(blank=True, max_length=50, null=True)),
                ('river', models.CharField(blank=True, max_length=50, null=True)),
                ('classification', models.CharField(blank=True, max_length=50, null=True)),
                ('rightsAndReproduction', models.CharField(blank=True, max_length=50, null=True)),
                ('linkResource', models.CharField(blank=True, max_length=50, null=True)),
                ('metadataDate', models.DateField(blank=True, max_length=50, null=True)),
                ('repository', models.CharField(blank=True, max_length=50, null=True)),
                ('objectURL', models.CharField(blank=True, max_length=50, null=True)),
                ('tags', models.CharField(blank=True, max_length=50, null=True)),
                ('objectWikidata_URL', models.CharField(blank=True, max_length=50, null=True)),
                ('isTimelineWork', models.BooleanField()),
                ('galleryNumber', models.IntegerField()),
                ('constituentID', models.IntegerField()),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('constituentULAN_URL', models.CharField(blank=True, max_length=50, null=True)),
                ('constituentWikidata_URL', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=20)),
            ],
        ),
    ]
