# Generated by Django 4.0 on 2021-12-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_app', '0003_alter_museumapicsv_artistbegindate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='museumapicsv',
            name='objectBeginDate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='museumapicsv',
            name='objectDate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='museumapicsv',
            name='objectEndDate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
