# Generated by Django 4.0 on 2021-12-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_app', '0004_alter_museumapicsv_objectbegindate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='museumapicsv',
            name='metadataDate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
