# Generated by Django 4.0 on 2021-12-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_app', '0006_alter_museumapicsv_artistdisplaybio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='museumapicsv',
            name='galleryNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
