# Generated by Django 4.0 on 2021-12-22 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_app', '0009_alter_museumapicsv_additionalimages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='museumapicsv',
            name='accessionNumber',
            field=models.CharField(max_length=50),
        ),
    ]
