# Generated by Django 4.0 on 2021-12-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_app', '0010_alter_museumapicsv_accessionnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='museumapicsv',
            name='constituentID',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
