# Generated by Django 4.0 on 2022-01-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_app', '0011_alter_museumapicsv_constituentid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileModel',
        ),
        migrations.AlterField(
            model_name='museumapicsv',
            name='primaryImage',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
