# Generated by Django 4.0 on 2022-01-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_app', '0012_delete_filemodel_alter_museumapicsv_primaryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='museumapicsv',
            name='primaryImage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
